### ISSUE TITLE
Error NO MODULE

### ISSUE THREAD

**Issue by DaZy4** [mahart-studio/kivystudio#33]
Error log:
E:\kivystudio\kivystudio>python main.py
[INFO   ] [Logger      ] Record log in C:\Users\a6415\.kivy\logs\kivy_20-06-07_1.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.2.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "C:\Users\a6415\AppData\Local\Programs\Python\Python38-32\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
[INFO   ] [Python      ] Interpreter at "C:\Users\a6415\AppData\Local\Programs\Python\Python38-32\python.exe"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "main.py", line 15, in <module>
     from kivystudio import tools
   File "..\kivystudio\__init__.py", line 2, in <module>
     from .filechooserthumbview import StudioFileChooserThumbView
 ModuleNotFoundError: No module named 'kivystudio.filechooserthumbview'

**Comment by allanjonis** [comment]
Same problem here.

**Comment by avour** [comment]
Looks like a simple import error, I would look into it
