### ISSUE TITLE
Top Bar menu crash when click

### ISSUE THREAD

**Issue by jhay06** [mahart-studio/kivystudio#36]
Traceback (most recent call last):
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 242, in create_handler
     return eval(value, idmap), bound_list
   File "D:\kivy\kivystudio\kivystudio\components\topmenu\dropmenu.kv", line 72, in <module>
     color: (self.parent.text_colors[0] if self.type=='text' else self.parent.text_colors[1]) if self.parent else (0,0,0,1)
 IndexError: list index out of range

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 695, in _apply_rule
     value, bound = create_handler(
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 245, in create_handler
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "D:\kivy\kivystudio\kivystudio\components\topmenu\dropmenu.kv", line 72:
 ...
      70:    padding: '20dp', 0
      71:    type: 'text'
 >>   72:    color: (self.parent.text_colors[0] if self.type=='text' else self.parent.text_colors[1]) if self.parent else (0,0,0,1)
      73:
      74:
 ...
 IndexError: list index out of range
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 242, in create_handler
     return eval(value, idmap), bound_list
   File "D:\kivy\kivystudio\kivystudio\components\topmenu\dropmenu.kv", line 72, in <module>
     color: (self.parent.text_colors[0] if self.type=='text' else self.parent.text_colors[1]) if self.parent else (0,0,0,1)

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "main.py", line 43, in <module>
     main()
   File "main.py", line 40, in main
     studio_app.run()
   File "main.py", line 34, in run
     super(KivyStudio, self).run()
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\base.py", line 391, in idle
     self.dispatch_input()
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy\_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy\_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 57, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "<string>", line 17, in <module>
   File "..\kivystudio\components\topmenu\__init__.py", line 37, in drop_menu
     setattr(self, menu_name, getattr(dropmenu, menu_name)())
   File "..\kivystudio\components\topmenu\dropmenu.py", line 21, in __init__
     super(FileTopMenu, self).__init__(**k)
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\uix\dropdown.py", line 214, in __init__
     super(DropDown, self).__init__(**kwargs)
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\uix\scrollview.py", line 539, in __init__
     super(ScrollView, self).__init__(**kwargs)
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\uix\widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\uix\widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 541, in apply
     self._apply_rule(
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 661, in _apply_rule
     child.apply_class_lang_rules(
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\uix\widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 541, in apply
     self._apply_rule(
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 661, in _apply_rule
     child.apply_class_lang_rules(
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\uix\widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 541, in apply
     self._apply_rule(
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 710, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "D:\kivy\kivystudio\kivystudio\components\topmenu\dropmenu.kv", line 72:
 ...
      70:    padding: '20dp', 0
      71:    type: 'text'
 >>   72:    color: (self.parent.text_colors[0] if self.type=='text' else self.parent.text_colors[1]) if self.parent else (0,0,0,1)
      73:
      74:
 ...
 BuilderException: Parser: File "D:\kivy\kivystudio\kivystudio\components\topmenu\dropmenu.kv", line 72:
 ...
      70:    padding: '20dp', 0
      71:    type: 'text'
 >>   72:    color: (self.parent.text_colors[0] if self.type=='text' else self.parent.text_colors[1]) if self.parent else (0,0,0,1)
      73:
      74:
 ...
 IndexError: list index out of range
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 242, in create_handler
     return eval(value, idmap), bound_list
   File "D:\kivy\kivystudio\kivystudio\components\topmenu\dropmenu.kv", line 72, in <module>
     color: (self.parent.text_colors[0] if self.type=='text' else self.parent.text_colors[1]) if self.parent else (0,0,0,1)

   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 695, in _apply_rule
     value, bound = create_handler(
   File "D:\Users\fmendoza\AppData\Local\Programs\Python\Python38\lib\site-packages\kivy\lang\builder.py", line 245, in create_handler
     raise BuilderException(rule.ctx, rule.line,

**Comment by 4lp3r** [comment]
I was have the same problem.
How to solve?
