### ISSUE TITLE
Getting Error when Run Main.py File

### ISSUE THREAD

**Issue by jsdpr1503** [mahart-studio/kivystudio#40]
Sir,

i am getting Error while running your code's main File

...
     24:            on_size: Clock.schedule_once(lambda dt: setattr(self, 'grid_len', int(self.width/(self.children[0].width+10))), 1)
     25:
>>   26:[StudioFileThumbEntry@IconWidget_]:
     27:    image: image
     28:    locked: False
...
Deprecated Kivy lang template syntax used "[StudioFileThumbEntry@IconWidget_]". Templates will be removed in a future version
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Loader      ] using a thread pool of 2 workers
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "C:\Users\J\Desktop\Python Projects\Git\kivystudio\kivystudio\main.py", line 43, in <module>
     main()
   File "C:\Users\J\Desktop\Python Projects\Git\kivystudio\kivystudio\main.py", line 40, in main
     studio_app.run()
   File "C:\Users\J\Desktop\Python Projects\Git\kivystudio\kivystudio\main.py", line 34, in run
     super(KivyStudio, self).run()
   File "C:\Python\3_9_1\lib\site-packages\kivy\app.py", line 950, in run
     runTouchApp()
   File "C:\Python\3_9_1\lib\site-packages\kivy\base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "C:\Python\3_9_1\lib\site-packages\kivy\base.py", line 347, in mainloop
     self.idle()
   File "C:\Python\3_9_1\lib\site-packages\kivy\base.py", line 387, in idle
     Clock.tick()
   File "C:\Python\3_9_1\lib\site-packages\kivy\clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "C:\Python\3_9_1\lib\site-packages\kivy\clock.py", line 776, in post_idle
     self._process_events()
   File "kivy\_clock.pyx", line 616, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 649, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 645, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File "C:\Python\3_9_1\lib\site-packages\kivy\uix\filechooser.py", line 711, in _update_files
     if self._create_files_entries():
   File "C:\Python\3_9_1\lib\site-packages\kivy\uix\filechooser.py", line 731, in _create_files_entries
     index, total, item = next(self._gitems_gen)
   File "C:\Python\3_9_1\lib\site-packages\kivy\uix\filechooser.py", line 852, in _generate_file_entries
     for index, total, item in self._add_files(path):
   File "C:\Python\3_9_1\lib\site-packages\kivy\uix\filechooser.py", line 901, in _add_files
     entry = self._create_entry_widget(ctx)
   File "C:\Users\J\Desktop\Python Projects\Git\kivystudio\kivystudio\..\kivystudio\widgets\filemanager\filechooserthumbview\__init__.py", line 258, in _create_entry_widget
     self.thumbnail_generator.run()
   File "C:\Users\J\Desktop\Python Projects\Git\kivystudio\kivystudio\..\kivystudio\widgets\filemanager\filechooserthumbview\__init__.py", line 447, in run
     if self.thread is None or not self.thread.isAlive():
 AttributeError: 'Thread' object has no attribute 'isAlive'

**Comment by tirkarthi** [comment]
PR to fix : https://github.com/mahart-studio/kivystudio/pull/42 . This is due to changes in Python 3.9 . You can incorporate the changes or use Python 3.8.

**Comment by avour** [comment]
Just merged the the PR, thanks @tirkarthi and @jsdpr1503
