### ISSUE TITLE
Kivystudio Notresponding and stops with error

### ISSUE THREAD

**Issue by infinite-dev22** [mahart-studio/kivystudio#46]
[INFO   ] [Logger      ] Record log in C:\Users\mwigo\.kivy\logs\kivy_22-06-12_32.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.2
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.4.5
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.3.0 - Build 20.19.15.4624'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) Iris(TM) Graphics 5100'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 3
[INFO   ] [GL          ] Shading version <b'4.30 - Build 20.19.15.4624'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
 --- Logging error ---
 Traceback (most recent call last):
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1083, in emit
     msg = self.format(record)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 927, in format
     return fmt.format(record)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\logger.py", line 291, in format
     record = copy.deepcopy(record)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\copy.py", line 172, in deepcopy
     y = _reconstruct(x, memo, *rv)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\copy.py", line 270, in _reconstruct
     state = deepcopy(state, memo)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\copy.py", line 146, in deepcopy
     y = copier(x, memo)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\copy.py", line 230, in _deepcopy_dict
     y[deepcopy(key, memo)] = deepcopy(value, memo)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\copy.py", line 172, in deepcopy
     y = _reconstruct(x, memo, *rv)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\copy.py", line 264, in _reconstruct
     y = func(*args)
 TypeError: __init__() missing 2 required positional arguments: 'line' and 'message'
 Call stack:
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\Scripts\kivystudio-script.py", line 33, in <module>
     sys.exit(load_entry_point('kivystudio==0.1.0', 'console_scripts', 'kivystudio')())
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\Scripts\kivystudio-script.py", line 25, in importlib_load_entry_point
     return next(matches).load()
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 77, in load
     module = import_module(match.group('module'))
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivystudio-0.1.0-py3.9.egg\kivystudio\main.py", line 25, in <module>
     from kivystudio.assembler import Assembler
   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivystudio-0.1.0-py3.9.egg\kivystudio\assembler.py", line 6, in <module>
     from kivystudio.widgets.filemanager import filemanager
   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivystudio-0.1.0-py3.9.egg\kivystudio\widgets\filemanager\__init__.py", line 2, in <module>
     from .filechooserthumbview import StudioFileChooserThumbView
   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivystudio-0.1.0-py3.9.egg\kivystudio\widgets\filemanager\filechooserthumbview\__init__.py", line 58, in <module>
     Builder.load_string("""
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\builder.py", line 372, in load_string
     parser = Parser(content=string, filename=fn)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\parser.py", line 483, in __init__
     self.parse(content)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\parser.py", line 593, in parse
     objects, remaining_lines = self.parse_level(0, lines)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\parser.py", line 675, in parse_level
     current_object = ParserRule(self, ln, name, rlevel)
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\parser.py", line 335, in __init__
     self._detect_selectors()
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\parser.py", line 379, in _detect_selectors
     self._build_template()
   File "C:\Users\mwigo\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\lang\parser.py", line 439, in _build_template
     Logger.warning(exception)
 Message: ParserException('Parser: File "<inline>", line 26:\n...\n     24:            on_size: Clock.schedule_once(lambda dt: setattr(self, \'grid_len\', int(self.width/(self.children[0].width+10))), 1)\n     25:\n>>   26:[StudioFileThumbEntry@IconWidget_]:\n     27:    image: image\n     28:    locked: False\n...\nDeprecated Kivy lang template syntax used "[StudioFileThumbEntry@IconWidget_]". Templates will be removed in a future version')
 Arguments: ()
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Loader      ] using a thread pool of 2 workers

[process exited with code 3221225512 (0xc0000028)]

**Comment by Domingez87** [comment]
I have same problem.
